# Generated by Django 4.2.1 on 2023-06-04 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Country')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('street', models.CharField(max_length=50, null=True, verbose_name='Street')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='Number of building')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('model', models.CharField(max_length=25, verbose_name='Model')),
                ('release', models.DateField(null=True, verbose_name='Release date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='TradeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Title')),
                ('unit_type', models.PositiveSmallIntegerField(choices=[(1, 'Factory'), (2, 'Retail Network'), (3, 'Individual entrepreneur')], default=1, verbose_name='Type of trade unit')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of debt')),
                ('level', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.contact', verbose_name='Contact')),
                ('products', models.ManyToManyField(blank=True, related_name='units', to='network.product', verbose_name='Products')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.tradeunit', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Trade unit',
                'verbose_name_plural': 'Trade units',
            },
        ),
    ]
